/* eslint-disable prettier/prettier */
export enum Permission {
  MANAGE_PROJECTS = 'MANAGE_PROJECTS',
  ASSIGN_PROJECT = 'ASSIGN_PROJECT',
  VIEW_ALL_PROJECTS = 'VIEW_ALL_PROJECTS',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_EMAIL_LOGS = 'VIEW_EMAIL_LOGS',
  CREATE_PROJECT = 'CREATE_PROJECT',
  VIEW_ALL_USERS = "VIEW_ALL_USERS",
  VIEW_OWN_PROJECTS = "VIEW_OWN_PROJECTS",
  UPDATE_PROJECT_STATUS = "UPDATE_PROJECT_STATUS",
  CREATE_USER = 'CREATE_USER'
}
