### Register admin user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "melissamakeba@gmail.com",
  "password": "Mel143",
  "name": "Admin user",
  "role": "ADMIN"
}

###Register a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com",
  "password": "Jona123",
  "name": "Jonathan Mulinge",
  "role": "USER"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "brianmwasbayo@gmail.com",
  "password": "Kishoyan12"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "melissa.waitituh@strathmore.edu",
  "password": "Mel0023"
}