### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "adminMel@example.com",
  "password": "Mel1233",
  "name": "Admin user",
  "role": "ADMIN"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "adminMel@example.com",
  "password": "Mel1233"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com",
  "password": "shal00j1010"
}