
### Create a new user
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjllNGI2OS0xOGQ1LTQ3NDItYmQ3My03M2RkZDZlODQzYTYiLCJlbWFpbCI6ImFkbWluTWVsQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzQ5OTUzNzY1LCJleHAiOjE3NTAwNDAxNjV9.oprodhyeUxRFZBm6R222Z91A8IyzJFSSgay_0jtq1BA

{
  "name": "Brian Mwangi",
  "email": "brian@gmail.com",
  "password": "shal00j1010",
  "role": "USER"
}


###

### Get all users
GET http://localhost:3000/users

###

### Get user by ID
GET http://localhost:3000/users/7d57e7dd-f95b-44f3-9f55-6d72e4d2e997

###

### Get user by email
GET http://localhost:3000/users/email/jonathanm@gmail.com

###

### Update user by ID
PATCH http://localhost:3000/users/7d57e7dd-f95b-44f3-9f55-6d72e4d2e997
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com"
}

###

### Delete user by ID
DELETE http://localhost:3000/users/7d57e7dd-f95b-44f3-9f55-6d72e4d2e997
